#############################################################################
# Makefile for building: project
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Aug 20 19:57:49 2014
# Project:  project.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile project.pro
#############################################################################

####### Compiler, tools and options

CC            = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -w -D_REENTRANT $(DEFINES) -g -Wall -fopenmp
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib -L/usr/lib/x86_64-linux-gnu  -lQtGui -lQtCore -lpthread 
LIBS2         = -lm 


####### Files
PROJECT_ROOT=.
SRCDIR = $(PROJECT_ROOT)/src/db
SRCDIR2 = $(PROJECT_ROOT)/src/GUI
OBJDIR = $(PROJECT_ROOT)/obj
BINDIR = $(PROJECT_ROOT)/bin
SRCS := $(wildcard $(SRCDIR)/*.cpp)
SRCS2 := $(wildcard $(SRCDIR2)/*.cpp)
INCS := $(wildcard $(SRCDIR)/*.h*)
INCS2 := $(wildcard $(SRCDIR2)/*.h*)
OBJS :=  $(SRCS:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)
OBJS2 :=  $(SRCS2:$(SRCDIR2)/%.cpp=$(OBJDIR)/%.o)
TARGET = generate_data
TARGET2 = drawing_app

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CC) $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CC) $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CC) $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CC) $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: $(SRCDIR2)/moc_mainwindow.cpp $(SRCDIR2)/moc_scribblearea.cpp $(TARGET) $(TARGET2) 

$(TARGET): $(OBJS) 
	$(CC) -w -g -o $@ $(LIBS) $(OBJS) -std=c++0x -fpermissive -fopenmp `pkg-config --cflags --libs opencv` 
	mv $(TARGET) $(BINDIR)


$(TARGET2):  $(OBJS2)  
	$(CC) $(LFLAGS) -w -g -o $@ $(LIBS2) $(OBJS2) $(LIBS) -std=c++0x -fopenmp -fpermissive `pkg-config --cflags --libs opencv` 


docs: doc/Doxyfile doc2/Doxyfile
	cd db_doc; doxygen Doxyfile; cd ..; cd GUI_doc; doxygen Doxyfile

clean:
	rm -f $(OBJDIR)/*.o $(TARGET)
	rm -f *~ core *.core
	rm ./bin/*
	rm drawing_app
	rm *jpg *anim
cleanDB:
	rm ./DatabaseFiles/*

cleandocs:
	cd db_doc; rm -rf html
	cd GUI_doc; rm -rf html

	
$(OBJS): $(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	$(CC) -w -g -c $< -o $@ -std=c++0x -fpermissive

$(OBJS2): $(OBJDIR)/%.o : $(SRCDIR2)/%.cpp
	$(CC) -g -c  $(CXXFLAGS) $(INCPATH) $< -o $@ -std=c++0x -fpermissive

$(SRCDIR2)/moc_mainwindow.cpp : $(SRCDIR2)/mainwindow.h
	moc -w -o $@ $<

$(SRCDIR2)/moc_scribblearea.cpp : $(SRCDIR2)/scribblearea.h
	moc -w -o $@ $<
